/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineDoctorAppointmentSystem;

import java.awt.HeadlessException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;

/**
 *
 * @author vinya
 */
public class DoctorDetails extends javax.swing.JFrame {

    private static String username= "root";
    private static String password= "";
    private static String dataConn= "jdbc:mysql://localhost:3306/users_db";

    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i,id,deleteItem;
    public String speciality;
    
    public DoctorDetails() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    /**
     *
     * @throws java.lang.ClassNotFoundException
     */
   public void upDateDB() throws ClassNotFoundException
   {
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           sqlConn = DriverManager.getConnection(dataConn,username,password);
           pst = sqlConn.prepareStatement("select * from doctordetails");
           
           rs = pst.executeQuery();
           ResultSetMetaData stData = rs.getMetaData();
           
           q = stData.getColumnCount();
           
           DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
           RecordTable.setRowCount(0);
           
           while(rs.next()){
               Vector columnData = new Vector();
               
               for(i=1;i<=q;i++)
               {
                   columnData.add(rs.getString("ID"));
                   columnData.add(rs.getString("DoctorId"));
                   columnData.add(rs.getString("Firstname"));
                   columnData.add(rs.getString("Lastname"));
                   columnData.add(rs.getString("Qualification"));
                   columnData.add(rs.getString("Speciality"));
                   columnData.add(rs.getString("fees"));
               }
               RecordTable.addRow(columnData);
           }
       }
       catch(SQLException ex)
       {
           JOptionPane.showMessageDialog(null, ex);
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtfirstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtDoctorid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtfees = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtqualification = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jtbnexit = new javax.swing.JButton();
        jtbnreset = new javax.swing.JButton();
        jtbnprint = new javax.swing.JButton();
        jtbnupdate = new javax.swing.JButton();
        jtbnadd = new javax.swing.JButton();
        jtbndelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtcontact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtlastname = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        combobox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Doctor Details");

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Full Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 120, 30));
        jPanel2.add(jtxtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 320, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctor Id:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 110, 30));
        jPanel2.add(jtxtDoctorid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fees:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 170, 30));

        jtxtfees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfeesActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtfees, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 190, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Speciality:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 130, 30));
        jPanel2.add(jtxtqualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 230, 30));

        jTable1.setBackground(new java.awt.Color(153, 255, 255));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Doctor Id", "Full Name", "Experience", "Qualification", "Speciality", "Contact", "Fees"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 740, 210));

        jtbnexit.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jtbnexit.setText("Back");
        jtbnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnexitActionPerformed(evt);
            }
        });
        jPanel2.add(jtbnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 420, 150, 50));

        jtbnreset.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jtbnreset.setText("Reset");
        jtbnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnresetActionPerformed(evt);
            }
        });
        jPanel2.add(jtbnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 150, 50));

        jtbnprint.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jtbnprint.setText("Print Data");
        jtbnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnprintActionPerformed(evt);
            }
        });
        jPanel2.add(jtbnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 200, 150, 50));

        jtbnupdate.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jtbnupdate.setText("Update Data");
        jtbnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnupdateActionPerformed(evt);
            }
        });
        jPanel2.add(jtbnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, 150, 50));

        jtbnadd.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jtbnadd.setText("Add New Data");
        jtbnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnaddActionPerformed(evt);
            }
        });
        jPanel2.add(jtbnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 50, 150, 50));

        jtbndelete.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jtbndelete.setText("Delete");
        jtbndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbndeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jtbndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 340, 150, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 100, 30));
        jPanel2.add(jtxtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 190, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Experience:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 110, 30));
        jPanel2.add(jtxtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Qualification:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 130, 30));

        combobox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiologist", "Gas", "Eye", "Neurologist", "ENT", "Lungs" }));
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });
        jPanel2.add(combobox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 230, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/female doctor.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male doctor.png"))); // NOI18N
        jLabel9.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnaddActionPerformed
        // TODO add your handling code here:
        try
       {
           Class.forName("com.mysql.jdbc.Driver");
           sqlConn = DriverManager.getConnection(dataConn,username,password);
           pst = sqlConn.prepareStatement("insert into doctordetails(DoctorId,Firstname,Lastname,Qualification,AdharNum,fees,Speciality)value(?,?,?,?,?,?,?)");
           
           pst.setString(1, jtxtDoctorid.getText()); 
           pst.setString(2, jtxtfirstname.getText());
           pst.setString(3, jtxtlastname.getText());
           pst.setString(4, jtxtqualification.getText());
           pst.setString(5, jtxtfees.getText());
           pst.setString(6, jtxtcontact.getText());
           pst.setString(7, speciality);

           
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(this, "Record Added Successfully");
           upDateDB();

       }
        catch(ClassNotFoundException | SQLException ex)
        {
            
            java.util.logging.Logger.getLogger(DoctorDetails.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jtbnaddActionPerformed
private JFrame frame;
    private void jtbnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnexitActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Are you sure you want to go back ?","Confirm Back",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            AdminMenu st = new AdminMenu();
            st.show();
            this.dispose();
        }
        
    }//GEN-LAST:event_jtbnexitActionPerformed

    private void jtbnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnresetActionPerformed
        // TODO add your handling code here:
        jtxtDoctorid.setText("");
        jtxtfirstname.setText("");
        jtxtlastname.setText("");
        jtxtqualification.setText("");
        jtxtcontact.setText("");
        jtxtfees.setText("");
    }//GEN-LAST:event_jtbnresetActionPerformed

    private void jtbnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnupdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         
         try
       {
           id = Integer.parseInt(RecordTable.getValueAt((SelectedRows), 0).toString());
           Class.forName("com.mysql.jdbc.Driver");
           sqlConn = DriverManager.getConnection(dataConn,username,password);
           pst = sqlConn.prepareStatement("update doctordetails set DoctorId=?,Firstname=?,Lastname=?,Address=?,fees=?,Speciality=?,Contact=? where ID=?");
           
           pst.setString(1, jtxtDoctorid.getText()); 
           pst.setString(2, jtxtfirstname.getText());
           pst.setString(3, jtxtlastname.getText());
           pst.setString(4, jtxtqualification.getText());
           pst.setString(5, jtxtfees.getText());
           pst.setString(7, jtxtcontact.getText());
           pst.setString(6, speciality);

           
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(this, "Record Updated Successfully");
           upDateDB();

       }
        catch(ClassNotFoundException | SQLException ex)
        {
            java.util.logging.Logger.getLogger(DoctorDetails.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_jtbnupdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
         
         jtxtDoctorid.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
         jtxtfirstname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
         jtxtlastname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
         jtxtqualification.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
         jtxtfees.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
         jtxtcontact.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
         

    }//GEN-LAST:event_jTable1MouseClicked

    private void jtbnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL,header,footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer Found", e.getMessage());
        }
    }//GEN-LAST:event_jtbnprintActionPerformed

    private void jtbndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbndeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();
        
        try
        {
            id = Integer.parseInt(RecordTable.getValueAt(SelectedRows,0).toString());
            
            deleteItem = JOptionPane.showConfirmDialog(null, "Confirm if you want to delete item ?", "Warning", JOptionPane.YES_NO_OPTION);
            if(deleteItem == JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
           sqlConn = DriverManager.getConnection(dataConn,username,password);
           pst = sqlConn.prepareStatement("delete from doctordetails  where ID=?");
           
           pst.setInt(1,id);
           pst.executeUpdate();
           JOptionPane.showMessageDialog(this, "Doctor Record Updated");
           upDateDB();
           
           jtxtDoctorid.setText("");
           jtxtfirstname.setText("");
           jtxtlastname.setText("");
           jtxtqualification.setText("");
           jtxtfees.setText("");
           jtxtcontact.setText("");
           

            }
        }
        catch(ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(DoctorDetails.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        catch(SQLException ex)
        {
            System.err.println(ex);
        }
    }//GEN-LAST:event_jtbndeleteActionPerformed

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        // TODO add your handling code here:
        speciality=combobox1.getSelectedItem().toString();
        
        
        
    }//GEN-LAST:event_combobox1ActionPerformed

    private void jtxtfeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorDetails().setVisible(true);
            }
        });
    }

    private void setLocationRelativeTO(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jtbnadd;
    private javax.swing.JButton jtbndelete;
    private javax.swing.JButton jtbnexit;
    private javax.swing.JButton jtbnprint;
    private javax.swing.JButton jtbnreset;
    private javax.swing.JButton jtbnupdate;
    private javax.swing.JTextField jtxtDoctorid;
    private javax.swing.JTextField jtxtcontact;
    private javax.swing.JTextField jtxtfees;
    private javax.swing.JTextField jtxtfirstname;
    private javax.swing.JTextField jtxtlastname;
    private javax.swing.JTextField jtxtqualification;
    // End of variables declaration//GEN-END:variables

}
