/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineDoctorAppointmentSystem;

import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


import static onlineDoctorAppointmentSystem.AvailableDoctors.doctor_id;
import static onlineDoctorAppointmentSystem.AvailableDoctors.doctor_name;


/**
 *
 * @author parth
 */
public class FixAppointment extends javax.swing.JFrame {

    /**
     * Creates new form SpecialityForm
     */
     private static String username= "root";
    private static String password= "";
    private static String myConn= "jdbc:mysql://localhost:3306/users_db";
    
    
    Connection sqlConn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    int q,i,id,deleteItem;
     
    
    
    public FixAppointment() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public void cdate(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        LocalDateTime now = LocalDateTime.now();
        Receipt.setText(Receipt.getText()+"\n"+dtf.format(now));
    }
    /**
     *
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        showReceipt = new javax.swing.JButton();
        BookAppointment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Receipt = new javax.swing.JTextArea();
        BACK = new javax.swing.JButton();
        Print1 = new javax.swing.JButton();
        jtxttime = new javax.swing.JTextField();
        jtxtPatient = new javax.swing.JTextField();
        Print2 = new javax.swing.JButton();
        jtxtdate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Book Appointment");

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Time:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 110, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, 30));

        jtxtPhone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtxtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPhoneActionPerformed(evt);
            }
        });
        jtxtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPhoneKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 330, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 30));

        showReceipt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        showReceipt.setText("Show");
        showReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showReceiptActionPerformed(evt);
            }
        });
        jPanel2.add(showReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 120, 50));

        BookAppointment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BookAppointment.setText("Book Appointment");
        BookAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAppointmentActionPerformed(evt);
            }
        });
        jPanel2.add(BookAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 210, 50));

        Receipt.setColumns(20);
        Receipt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Receipt.setRows(5);
        jScrollPane1.setViewportView(Receipt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 500, 440));

        BACK.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BACK.setText("Back");
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        jPanel2.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 480, 120, 50));

        Print1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Print1.setText("Payment");
        Print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print1ActionPerformed(evt);
            }
        });
        jPanel2.add(Print1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, 120, 50));

        jtxttime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jtxttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 440, 40));

        jtxtPatient.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jtxtPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 440, 40));

        Print2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Print2.setText("Print");
        Print2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Print2ActionPerformed(evt);
            }
        });
        jPanel2.add(Print2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, 120, 50));

        jtxtdate.setDateFormatString("dd-MM-yy");
        jPanel2.add(jtxtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 330, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/female doctor.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male doctor.png"))); // NOI18N
        jLabel9.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1172, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showReceiptActionPerformed
        // TODO add your handling code here:
        Receipt.setText("**********************************\n");
        Receipt.setText(Receipt.getText()+"*       Your Appointment Receipt       *\n");
        Receipt.setText(Receipt.getText()+"**********************************\n");
        
        SimpleDateFormat dcn = new SimpleDateFormat("dd-MM-yyyy");
        String date = dcn.format(jtxtdate.getDate() );
        cdate();
//        Receipt.setText(Receipt.getText()+"\n"+date);
        
        Receipt.setText(Receipt.getText()+"\n\nName: "+jtxtPatient.getText()+"\n");
        Receipt.setText(Receipt.getText()+"Doctor's ID: "+doctor_id);
        Receipt.setText(Receipt.getText()+"\nDoctor's Name: "+doctor_name+"\n");
        Receipt.setText(Receipt.getText()+"\nDate: "+date.toString()+"\n");
        Receipt.setText(Receipt.getText()+"Time: "+jtxttime.getText()+"\n");
        Receipt.setText(Receipt.getText()+"Contact: "+jtxtPhone.getText()+"\n");


    }//GEN-LAST:event_showReceiptActionPerformed

    private void Print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print1ActionPerformed
        // TODO add your handling code here:
       
       PaymentDummy li = new PaymentDummy();
       li.show();
       this.dispose();
    }//GEN-LAST:event_Print1ActionPerformed

    private void BookAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAppointmentActionPerformed
        // TODO add your handling code here:
          try
       {
           Class.forName("com.mysql.jdbc.Driver");
           sqlConn = DriverManager.getConnection(myConn,username,password);
           pst = sqlConn.prepareStatement("insert into patientdetails(patient,DoctorId,date,time,contact)value(?,'"+doctor_id+"',?,?,?)");
           
           pst.setString(1, jtxtPatient.getText()); 
           pst.setString(2, DateFormat.getDateInstance().format(jtxtdate.getDate()));
           pst.setString(3, jtxttime.getText());
           pst.setString(4, jtxtPhone.getText());
           
           
           pst.executeUpdate();
           
           JOptionPane.showMessageDialog(this, "Your Appointment is fixed");
           
           
           
           

       }
        catch(ClassNotFoundException | SQLException ex)
        {
            
            java.util.logging.Logger.getLogger(DoctorDetails.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
        
                   
                    
       
    }//GEN-LAST:event_BookAppointmentActionPerformed

    private void jtxtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPhoneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtxtPhoneActionPerformed

    private void jtxtPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPhoneKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtPhoneKeyTyped

    private void Print2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Print2ActionPerformed
        // TODO add your handling code here:
       try
        {
            Receipt.print();
        }
        catch(PrinterException e)
        {
            
        }
    }//GEN-LAST:event_Print2ActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        // TODO add your handling code here:
        AvailableDoctors pr = new AvailableDoctors();
        pr.show();
        this.dispose();
                
    }//GEN-LAST:event_BACKActionPerformed
    
    
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FixAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FixAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FixAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FixAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FixAppointment().setVisible(true);
            }
        });
    }

    private void setLocationRelativeTO(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK;
    private javax.swing.JButton BookAppointment;
    private javax.swing.JButton Print1;
    private javax.swing.JButton Print2;
    private javax.swing.JTextArea Receipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtxtPatient;
    private javax.swing.JTextField jtxtPhone;
    private com.toedter.calendar.JDateChooser jtxtdate;
    private javax.swing.JTextField jtxttime;
    private javax.swing.JButton showReceipt;
    // End of variables declaration//GEN-END:variables
}
