/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineDoctorAppointmentSystem;

//import com.sun.jdi.connect.spi.Connection;
import java.sql.*;
import javax.swing.JOptionPane;



/**
 *
 * @author vinya
 */
public class SpecialityForm extends javax.swing.JFrame {

    /**
     * Creates new form SpecialityForm
     */

    
    private static String username= "root";
    private static String password= "";
    private static String myConn= "jdbc:mysql://localhost:3306/users_db";
    public static Connection sqlConn = null;
    public static PreparedStatement pst = null;
    public static ResultSet rs = null;
    
    public static String speciality;

    
    
//    private void ViewDatafromDB(String speciality){
//        try{
//           Class.forName("com.mysql.jdbc.Driver");
//           sqlConn = DriverManager.getConnection(myConn,username,password);
//           pst = sqlConn.prepareStatement("select * from doctordetails where Speciality = '" + speciality + "'");
//           ResultSet rs = pst.executeQuery();
//           
//           if(rs.next()){
//               for(int i=0;i<5;i++){
//               doctor_name[i] = rs.getString(3);
//               doctor_experience[i] = rs.getString(4);
//               doctor_qualification[i] = rs.getString(5);
//               }
//           }
//           
//           
//           
//           
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
//    }
    
    
    public SpecialityForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    /**
     *
     */
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lungs = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Cardiobutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        eye = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ent = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        gas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        brain = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Speciality");

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lungs.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 20, 140, 140));

        lungs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lungs.setText("Pulmonologist");
        lungs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lungs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lungsMouseClicked(evt);
            }
        });
        jPanel2.add(lungs, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, 180, 39));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Cardio.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, 114));

        Cardiobutton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cardiobutton.setText("Cardiologist");
        Cardiobutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cardiobutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CardiobuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CardiobuttonMouseEntered(evt);
            }
        });
        Cardiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CardiobuttonActionPerformed(evt);
            }
        });
        jPanel2.add(Cardiobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 150, 39));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eye.jpg"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 140, 140));

        eye.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        eye.setText("Ophthalmologist");
        eye.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        jPanel2.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 190, 39));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ent.png"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 140, 130));

        ent.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ent.setText("Otolaryngologist");
        ent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entMouseClicked(evt);
            }
        });
        jPanel2.add(ent, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 200, 39));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Gas.jpeg"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 140, 140));

        gas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gas.setText("Gastroenterologist");
        gas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gasMouseClicked(evt);
            }
        });
        jPanel2.add(gas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 210, 39));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Neurologist.jpg"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 140, 140));

        brain.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        brain.setText("Neurologist");
        brain.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        brain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brainMouseClicked(evt);
            }
        });
        jPanel2.add(brain, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 160, 39));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/female doctor.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male doctor.png"))); // NOI18N
        jLabel9.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CardiobuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardiobuttonMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_CardiobuttonMouseEntered

    private void CardiobuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CardiobuttonMouseClicked
        // TODO add your handling code here:
        AvailableDoctors ds = new AvailableDoctors();
        ds.show();
        dispose();
        ViewDatafromDB("Cardiologist");
    }//GEN-LAST:event_CardiobuttonMouseClicked

    private void entMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entMouseClicked
        // TODO add your handling code here:
        AvailableDoctors ds = new AvailableDoctors();
        ds.show();
        dispose();
        ViewDatafromDB("Ent");
    }//GEN-LAST:event_entMouseClicked

    private void lungsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lungsMouseClicked
        // TODO add your handling code here:
        AvailableDoctors ds = new AvailableDoctors();
        ds.show();
        dispose();
        ViewDatafromDB("Lungs");
    }//GEN-LAST:event_lungsMouseClicked

    private void gasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gasMouseClicked
        // TODO add your handling code here:
        AvailableDoctors ds = new AvailableDoctors();
        ds.show();
        dispose();
        ViewDatafromDB("Gas");
    }//GEN-LAST:event_gasMouseClicked

    private void brainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brainMouseClicked
        // TODO add your handling code here:
        AvailableDoctors ds = new AvailableDoctors();
        ds.show();
        dispose();
        ViewDatafromDB("Brain");
    }//GEN-LAST:event_brainMouseClicked

    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked
        // TODO add your handling code here:
        AvailableDoctors ds = new AvailableDoctors();
        ds.show();
        ViewDatafromDB("Eye");
        dispose();

    }//GEN-LAST:event_eyeMouseClicked

    
    
    
    
    private void CardiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CardiobuttonActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_CardiobuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpecialityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpecialityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpecialityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpecialityForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpecialityForm().setVisible(true);
            }
        });
    }

    private void setLocationRelativeTO(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cardiobutton;
    private javax.swing.JButton brain;
    private javax.swing.JButton ent;
    private javax.swing.JButton eye;
    private javax.swing.JButton gas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lungs;
    // End of variables declaration//GEN-END:variables

    private void ViewDatafromDB(String s) {
        speciality=s;
        
    }
}
